const menu = document.getElementById('menu')
const cartBtn = document.getElementById('cart-btn')
const cartModal = document.getElementById('Cart')
const cartItems = document.getElementById('cart-items')
const cartTotal = document.getElementById('cart-total')
const concluirBtn = document.getElementById('concluir-btn')
const closeBtn = document.getElementById('close-btn')
const cartCounter = document.getElementById('cart-count')